### ISSUE TITLE
Add CDS based benchs

### ISSUE THREAD

**Issue by sdeleuze** [dsyer/spring-boot-startup-bench#5]
See http://mjg123.github.io/2017/10/02/JVM-startup.html

**Comment by dsyer** [comment]
Please see `JsaBenchmark`. From the README:

```
 JsaBenchmark.basicThin                      avgt   10  5.725 ± 0.460   s/op
 JsaBenchmark.sharedClasses                  avgt   10  4.302 ± 0.203   s/op
 JsaBenchmark.thinMain                       avgt   10  4.808 ± 0.161   s/op
```

So it's about 10% faster for Petclinic. I didn't think that was dramatic enough to warrant a big push, given that in Java 8 it's a commercial only feature. I tried the same benchmark with Java 9 (Hotspot and J9) and the result wasn't even as good as 10%, so it doesn't seem worth pursuing aggressively. Probably the article you linked to has such a simple app that it makes a bigger difference.

**Comment by dsyer** [comment]
Update: I re-did the analysis, and also added a "vanilla" `CdsBenchmark` (not using commercial features).

```
Benchmark                   Mode  Cnt  Score   Error  Units
CdsBenchmark.sharedClasses  avgt   10  2.871 ± 0.088   s/op
CdsBenchmark.thinMain       avgt   10  2.933 ± 0.154   s/op
JsaBenchmark.sharedClasses  avgt   10  2.893 ± 0.068   s/op
JsaBenchmark.thinMain       avgt   10  2.898 ± 0.085   s/op
```

So there is really nothing in it (which is what I remembered from the JDK9 results). The difference in the old results is probably entirely explained by the effect of `-noverify`, which I forgot to include in the non-shared classes execution.

This is a PetClinic with Boot 1.4.6.
